<a href="https://colab.research.google.com/github/Rajnish379/Machine_Learning/blob/main/conv_demo_rmalred1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv2D, Flatten, Dense, ReLU
import tensorflow as tf
import numpy as np

#model = Sequential([
#    Input(shape=(3, 3, 1)),
#    Conv2D(1, kernel_size=(2, 2), activation='relu'),
#    Flatten(),
#    Dense(1, activation='sigmoid')
#])


# Input layer
input_layer = Input(shape=(3, 3, 1))

# Convolutional layer
custom_kernel_initializer = tf.constant_initializer(-0.5)
custom_bias_initializer = tf.constant_initializer(1.5)
conv_layer = Conv2D(1, kernel_size=(2, 2), strides=(1, 1),
                    kernel_initializer=custom_kernel_initializer,
                    bias_initializer=custom_bias_initializer)(input_layer)
conv_activation = ReLU()(conv_layer)

# Flatten layer
flatten_layer = Flatten()(conv_activation)

# Dense (fully connected) layer
dense_layer = Dense(1, activation='sigmoid',
                    #kernel_initializer='ones',
                    #bias_initializer='zeros'
                   )(flatten_layer)

model = Model(inputs=input_layer, outputs=dense_layer)

# Define a new model that outputs activations from each layer
activation_model = Model(inputs=input_layer, outputs=[conv_layer, conv_activation, flatten_layer, dense_layer])

# Input image
input_image = np.array([[[1], [1], [1]],
                        [[1], [1], [1]],
                        [[0], [0], [0]]],

                       #add more images like the 3x3 image above

                       ).reshape(1, 3, 3, 1)

# Get activations
activations = activation_model.predict(input_image)

# Print the activations for each layer
for i, activation in enumerate(activations):
    print(f"Activation Layer {i}: \n{activation}\n")

# Compile the original model
model.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(input_image, np.array([0]), epochs=100, verbose=1)

# Get updated output (activation of the top layer)
activation_model = Model(inputs=input_layer, outputs=[conv_layer, conv_activation, flatten_layer, dense_layer])
activations = activation_model.predict(input_image)
print(f"{activations[-1]=}")


1/1 [==============================] - 0s 235ms/step
Activation Layer 0: 
[[[[-0.5]
   [-0.5]]

  [[ 0.5]
   [ 0.5]]]]

Activation Layer 1: 
[[[[0. ]
   [0. ]]

  [[0.5]
   [0.5]]]]

Activation Layer 2: 
[[0.  0.  0.5 0.5]]

Activation Layer 3: 
[[0.6082005]]

Epoch 1/100
1/1 [==============================] - 1s 861ms/step - loss: 0.9370 - accuracy: 0.0000e+00
Epoch 2/100
1/1 [==============================] - 0s 15ms/step - loss: 0.9230 - accuracy: 0.0000e+00
Epoch 3/100
1/1 [==============================] - 0s 12ms/step - loss: 0.9095 - accuracy: 0.0000e+00
Epoch 4/100
1/1 [==============================] - 0s 12ms/step - loss: 0.8964 - accuracy: 0.0000e+00
Epoch 5/100
1/1 [==============================] - 0s 16ms/step - loss: 0.8837 - accuracy: 0.0000e+00
Epoch 6/100
1/1 [==============================] - 0s 17ms/step - loss: 0.8715 - accuracy: 0.0000e+00
Epoch 7/100
1/1 [==============================] - 0s 11ms/step - loss: 0.8596 - accuracy: 0.0000e+00
Epoch 8/100
1/1 [=======

In [ ]:
model.fit(input_image, np.array([0]), epochs=100, verbose=0)
activation_model = Model(inputs=input_layer, outputs=[conv_layer, conv_activation, flatten_layer, dense_layer])
activations = activation_model.predict(input_image)
print(f"{activations[-1]=}")


1/1 [==============================] - 0s 111ms/step
activations[-1]=array([[0.30891418]], dtype=float32)


In [ ]:
conv_layer_weights = model.layers[1].get_weights()

filter_weights = conv_layer_weights[0]  # This is a 4D tensor for Conv2D weights: (filter_height, filter_width, input_channels, output_channels)

first_filter_weights = filter_weights[:, :, 0, 0]  # For the first filter
print("First filter weights:\n", first_filter_weights)


First filter weights:
 [[-0.66929626 -0.66929626]
 [-0.5        -0.5       ]]
